### ISSUE TITLE
KEP 14(dup): Dynamic Audit Configuration

### ISSUE THREAD

**Issue by jdumars** [kubernetes-sigs/architecture-tracking#14]
https://github.com/kubernetes/community/pull/2188

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/pull/67547

**Comment by liggitt** [comment]
API review in progress in kubernetes/kubernetes#67547

**Comment by liggitt** [comment]
/assign lavalamp
(matching assignment of API PR)
