### ISSUE TITLE
CONFORMANCE: PVC/PV conformance testing discussion

### ISSUE THREAD

**Issue by jdumars** [kubernetes-sigs/architecture-tracking#4]
https://github.com/kubernetes/kubernetes/issues/65155

**Comment by spiffxp** [comment]
>Core conformance: All Kubernetes distros must pass
> - In-tree ephemeral volumes like emptydir, secrets, configmaps, downward api, etc (these already exist, maybe more can be added)
> - Hostpath
> - PVC/PV features that don't require a specific volume plugin: pre-binding, PV protection, Retain reclaim policy, etc.

eg: atomic writer volume subpaths https://github.com/kubernetes/kubernetes/pull/66871

**Comment by bgrant0607** [comment]
Closing in favor of the original issue.

Note that kubernetes/kubernetes#66871 wasn't about PV/PVC.
