### ISSUE TITLE
API Review: storage snapshot CRD binding review

### ISSUE THREAD

**Issue by jdumars** [kubernetes-sigs/architecture-tracking#44]
Design spec: https://github.com/kubernetes/community/pull/2335
Add API PR: https://github.com/kubernetes-csi/external-snapshotter/pull/6

**Comment by jingxu97** [comment]
Thanks @jdumars, could you please let us know what is the next step for this review? Thanks!

**Comment by jdumars** [comment]
@jingxu97 I have requested one of the reviewers to be assigned. I'll let you know when that happens and we'll coordinate from there. Thanks for your patience!

**Comment by jdumars** [comment]
Reference discussion [here](https://groups.google.com/forum/#!msg/kubernetes-sig-architecture/1tp8cNtmCn0/94zn87Y_DwAJ) on [kubernetes-sig-architecture](https://groups.google.com/forum/#!forum/kubernetes-sig-architecture)

**Comment by thockin** [comment]
This review is complete and approved.
