### ISSUE TITLE
API Review: RunAsGroup in PodSecurityPolicy

### ISSUE THREAD

**Issue by liggitt** [kubernetes-sigs/architecture-tracking#49]
https://github.com/kubernetes/kubernetes/pull/67802
https://github.com/kubernetes/features/issues/213
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/runas-groupid.md

**Comment by liggitt** [comment]
review in progress in https://github.com/kubernetes/kubernetes/pull/67802

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/67802 merged, is this done?

**Comment by liggitt** [comment]
Yes

/close
