### ISSUE TITLE
API Review: CSI Inline Volume

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-sigs/architecture-tracking#54]
Requesting review for API changes to implement support for the ability to nest CSI volume declarations within pod specs

* KEP - [CSI Inline Volume](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190122-csi-inline-volumes.md)
* PR - https://github.com/kubernetes/kubernetes/pull/74086
* Submitter @vladimirvivien

**Comment by liggitt** [comment]
thanks for following the documented process... we're actually [reworking that](https://github.com/kubernetes/community/pull/3261) to make it simpler and take advantage of artifacts people are already setting up.

Your [inline volume PR](https://github.com/kubernetes/kubernetes/pull/74086) is assigned for review in https://github.com/orgs/kubernetes/projects/13#card-17727405 and you can follow the status updates in your PR
